version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - BSCSCAN_API_KEY=${BSCSCAN_API_KEY}
      - POLYGONSCAN_API_KEY=${POLYGONSCAN_API_KEY}
      - BASESCAN_API_KEY=${BASESCAN_API_KEY}
      - GAME_API_KEY=${GAME_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./app:/app/app
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
