services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - DOPPLER_PROJECT=${DOPPLER_PROJECT}
      - DOPPLER_ENVIRONMENT=${DOPPLER_ENVIRONMENT}
      - DB_HOST=postgres:5432
    volumes:
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
      - ./app:/app/app
    # command: doppler run -- poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
      - postgres
    restart: always

  postgres:
    image: postgres:latest
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    expose:
      - 6379
    command: redis-server --bind 0.0.0.0

  worker:
    build:
      context: .
    depends_on:
      - redis
    # command: doppler run -- rq worker high low --url redis://redis:6379
    command: rq worker high low --url redis://redis:6379
    env_file:
      - .env
    links:
      - redis
    volumes:
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
      - ./app:/app/app
    restart: always

volumes:
  redis_data:
  postgres_data:
