version: "3.8"

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - BSCSCAN_API_KEY=${BSCSCAN_API_KEY}
      - POLYGONSCAN_API_KEY=${POLYGONSCAN_API_KEY}
      - BASESCAN_API_KEY=${BASESCAN_API_KEY}
      - GAME_API_KEY=${GAME_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - REDIS_HOST=${REDIS_HOST}
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    expose:
      - 6379
    command: redis-server --bind 0.0.0.0

  worker:
    build:
      context: .
    depends_on:
      - redis
    command: rq worker --url redis://redis:6379
    environment:
      - REDIS_HOST=${REDIS_HOST}
    links:
      - redis

volumes:
  redis_data:
