# fly.toml app configuration file generated for certaik-api-staging on 2025-01-06T20:07:01-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'certaik-api-staging'
primary_region = 'bos'

[build]

[processes]
  api = 'poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['api']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
