# fly.toml app configuration file generated for certaik-api on 2024-12-27T19:39:51-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "certaik-api-prod"
primary_region = "bos"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["api"]

[processes]
  api = "poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"