CONTRACT_TAG = "contract"
AUDIT_TAG = "audit"
USER_TAG = "user"
APP_TAG = "app"
PLATFORM_TAG = "platform"
CODE_EXAMPLE_TAG = "basic implementation"
CODE_EXAMPLE_APP_TAG = "basic app implementation"

TAG_GROUP_CORE = "Core Features"
TAG_GROUP_MANAGEMENT = "Management"
TAG_GROUP_MISC = "Misc"
TAG_GROUP_EXAMPLES = "Examples"
