global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'worker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['worker:9192']