{
 "title": "API Metrics Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Tasks Duration (s)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasks_duration_seconds_bucket{instance=\"worker:9192\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Active WS connections",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "h": 8, "w": 12 },
   "targets": [
    { "expr": "sum(websockets_active_total)", "legendFormat": "Active WS Connections" }
   ]
  },
  {
   "title": "API Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total[5m])) by (method, endpoint, status_code)",
     "legendFormat": "{{method}} {{endpoint}} ({{status_code}})"
    }
   ]
  },
  {
   "title": "Active API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(api_active_requests_total)", "legendFormat": "Active Requests" }
   ]
  },
  {
   "title": "Total Tasks by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "tasks_total", "legendFormat": "{{type}}" }
   ]
  }
 ]
}