{
 "title": "DB",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number of Audits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__time(created_at), \n       sum(count(*)) OVER (ORDER BY created_at) as \"all\",\n       sum(CASE WHEN status = 'failed' THEN 1 ELSE 0 END) OVER (ORDER BY created_at) as \"failed\"\nFROM (\n    SELECT id, status, created_at\n    FROM audit ORDER BY created_at\n) AS subq\nGROUP BY created_at, status;"
    }
   ]
  },
  {
   "title": "Number of Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__time(created_at), sum(count(*)) OVER (ORDER BY created_at) as \"all\"\nFROM (\n    SELECT id, created_at\n    FROM \"user\" ORDER BY created_at\n) AS subq\nGROUP BY created_at;"
    }
   ]
  },
  {
   "title": "Registered Apps",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "rawSql": "SELECT * FROM app LIMIT 50 " }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"user\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Audits",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "rawSql": "SELECT * FROM audit LIMIT 50 " }
   ]
  },
  {
   "title": "Contracts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM contract LIMIT 50 "
    }
   ]
  },
  {
   "title": "Findings",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT * FROM finding LIMIT 50 "
    }
   ]
  }
 ]
}