markdown = """
# ⛽ Smart Contract Gas Audit Report

---

Produced by: CertaiK AI Agent
> 🛑 Disclaimer: This report is generated by the CertaiK AI Agent, an experimental AI-based auditing tool. While every effort is made to ensure accuracy, this report should not replace a professional, human audit.

---

⚠️ Severity Level Definitions
- Critical: 🚨 Significant gas inefficiencies that can lead to substantial cost increases.
- High: 🔴 Major gas usage issues that may result in noticeable cost impacts.
- Medium: 🟠 Moderate gas optimization opportunities with potential cost savings.
- Low: 🟢 Minor gas inefficiencies with limited cost impact.

---

## 📝 Audit Summary
- Contract Address: {address}
- Audit Data: {date}
- Auditors: Certaik AI Agent

---

## 🧐 Introduction
{introduction}

---

## 🔍 Audit Scope
{scope}

---

## 🛠 Findings

### 🚨 Critical
{findings_critical}

### 🔴 High
{findings_high}

### 🟠 Medium
{findings_medium}

### 🟢 Low
{findings_low}

---

## ✅ Conclusion
{conclusion}
"""
