---
    name: CI
    on: [ workflow_dispatch, push, pull_request ]
    jobs:
      python:
        uses: lpenz/ghworkflow-python/.github/workflows/python.yml@v0.8.1
        with:
          coveralls: true
          codecov: true
          deb: true
          publish_pypi: false 
          publish_github_release: true
          publish_packagecloud: false 
          publish_packagecloud_repository: |
            ["debian/debian/bullseye", "ubuntu/ubuntu/focal"]