name: Run Tests

on:
  push:
    branches: [ main, prod ]
  pull_request:
    branches: [ main, prod ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build test image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: certaik-api-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run tests
      run: |
        docker run --rm certaik-api-test:latest poetry run pytest -v
      # This will fail the workflow if tests fail

    # Optional: Add test coverage reporting
    - name: Run tests with coverage
      run: |
        docker run --rm certaik-api-test:latest poetry run pytest --cov=app --cov-report=xml -v
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false 